# KNN

## Exercises
Create a new notebook, knn_model, and work with the titanic dataset to answer the following:

### Highlights

############# Markdown parser in Jupyter notebooks ##################

<div class="alert alert-block alert-info"> <b>NOTE</b>
 Use blue boxes for Tips and notes.
</div>

<div class="alert alert-block alert-success"> 
 Use green boxes sparingly, and only for some specific purpose that the other boxes can't cover. For example, if you have a lot of related content to link to, maybe   you decide to use green boxes for related links from each section of a notebook. 
</div>

<div class="alert alert-block alert-warning"> 
 Use yellow boxes for examples that are not inside code cells, or use for mathematical formulas if needed. 
</div>

<div class="alert alert-block alert-danger">
 In general, just avoid the red boxes. 
</div>

### Imports

In [2]:
import acquire
import prepare

import pandas as pd
import numpy as np

# matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

from pydataset import data

<div class="alert alert-block alert-success">
Load your DATA, PREPARE, SPLIT, CONVERT to X_train and y_train.
</div>

In [3]:
# Get your titanic data
titanic_df = acquire.get_titanic_data()

# Clean the new dataset using the new function called prep_titanic
titanic_df = prepare.prep_titanic(titanic_df)

# Prepare and Split my data
train, validate, test = prepare.split_function(titanic_df, 'survived')

# ------------------------
# Lets drop 'passenger_id', 'survived', 'sex', 'embarked' because they either are objects or don't add value to the data.
# Also, we need to remove the 'survived' column because is our TARGET.
# Also, lets convert train, validate and test. 
X_train = train.drop(columns = ['passenger_id', 'survived', 'sex', 'embarked'])
X_validate = validate.drop(columns = ['passenger_id', 'survived', 'sex', 'embarked'])
X_test = test.drop(columns = ['passenger_id', 'survived', 'sex', 'embarked'])

# ------------------------
# Set a target
target = 'survived'

# 'y' variable are series
y_train = train[target]
y_validate = validate[target]
y_test = test[target]

# ------------------------
# calculate baseline accuracy
# baseline_accuracy = (train.servived == 0)
baseline_accuracy = 329 / (329+205)
print(f'Baseline accuracy: {baseline_accuracy}')

csv file found and loaded
Baseline accuracy: 0.6161048689138576


#### 1. Fit a K-Nearest Neighbors classifier to your training sample and transform (i.e. make predictions on the training sample)

##### 1a. Create the kNN object

In [5]:
# set to defaults
knn1 = KNeighborsClassifier(n_neighbors=5, weights='uniform')

##### 1b. Fit the model to the training data

In [6]:
knn1.fit(X_train, y_train)

KNeighborsClassifier()

##### 1c. Make predictions

In [11]:
y_pred1 = knn1.predict(X_train)

/opt/homebrew/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:237: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [12]:
y_pred1[:5]

array([0, 1, 1, 0, 0])

##### 1d. Estimate Probability

In [9]:
y_pred_proba1 = knn1.predict_proba(X_train)
y_pred_proba1[:5]

array([[0.6, 0.4],
       [0.4, 0.6],
       [0.4, 0.6],
       [0.6, 0.4],
       [1. , 0. ]])

In [13]:
knn1.classes_

array([0, 1])

#### 2. Evaluate your results using the model score, confusion matrix, and classification report.

##### Confusion matrix

In [15]:
#conf matrix
confusion_matrix(y_train, y_pred1) #rows, columns

array([[280,  49],
       [ 50, 155]])

#### 3. Print and clearly label the following: Accuracy, true positive rate, false positive rate, true negative rate, false negative rate, precision, recall, f1-score, and support.

#### 4. Run through steps 1-3 setting k to 10

#### 5. Run through steps 1-3 setting k to 20

#### 6. What are the differences in the evaluation metrics? Which performs better on your in-sample data? Why?

#### 7. Which model performs best on our out-of-sample data from validate?