# Evaluation

## Exercises

### 1. Create a new file named model_evaluation.py or model_evaluation.ipynb for these exercises.

### 2. Given the following confusion matrix, evaluate (by hand) the model's performance.


|                  | (AP) actual dog     | (AN) actual cat|                          |
|:-----------------|--------------------:|---------------:|--------------------------:
| (PP) pred dog    | (TP)             46 | (FP)        13 | Precision/PPV:TP/(TP+FP) |
| (PN) pred cat    | (FN)              7 | (TN)        34 | NPV: TN/(TN_FN).         |
|                  | Recall/Sensitivity: | Specificity:   | Accuracy =               |
|                  | TP/(TP+FN)          | TN/(FP+TN)     | (TP+TN)/                 |
|                  |                     |                | (TP+FP+FN+TN)            |


>In the context of this problem, what is a false positive?
>> FP: We predicted they were dogs and they were actual cats (13 times)

>In the context of this problem, what is a false negative?
>> FN: We predicted they were cats and they were actual dogs (7 times)

>How would you describe this model?
>> TP: We predicted they were dogs and they were actual dogs (46 times)

>> TN: We predicted they were cats and they were actual cats (34 times)

>> FP: We predicted they were dogs and they were actual cats (13 times)

>> FN: We predicted they were cats and they were actual dogs (7 times)

In [5]:
tp = 46

tn = 34

fp = 13

fn = 7

In [10]:
accuracy = (tp + tn) / (tp + tn + fp + fn)

recall = tp / (tp + fn)

precision = tp / (tp + fp)

print(f"""Dog-classifier (where 'DOG' is the psoitve prediction)

True Positives: {tp}
False Positives: {fp}
False Negatives: {fn}
True Negatives: {tn}

---------------------

Baseline is: Dog - highest frequency
Accuarcy is: {accuracy}
Recall is: {recall}
Precision is: {precision}
""")



Dog-classifier (where 'DOG' is the psoitve prediction)

True Positives: 46
False Positives: 13
False Negatives: 7
True Negatives: 34

---------------------

Baseline is: Dog - highest frequency
Accuarcy is: 0.8
Recall is: 0.8679245283018868
Precision is: 0.7796610169491526



### 3. You are working as a datascientist working for Codeup Cody Creator (C3 for short), a rubber-duck manufacturing plant.

    Unfortunately, some of the rubber ducks that are produced will have defects. Your team has built several models that try to predict those defects, and the data from their predictions can be found here.

    Use the predictions dataset and pandas to help answer the following questions:

### Imports

In [12]:
import pandas as pd

#stats
from sklearn.metrics import confusion_matrix

In [13]:
filename = 'c3.csv'

In [14]:
c3_df = pd.read_csv(filename)

In [15]:
c3_df.head()

actual     model1  model2     model3
0  No Defect  No Defect  Defect  No Defect
1  No Defect  No Defect  Defect     Defect
2  No Defect  No Defect  Defect  No Defect
3  No Defect     Defect  Defect     Defect
4  No Defect  No Defect  Defect  No Defect

In [16]:
c3_df.actual.value_counts()

No Defect    184
Defect        16
Name: actual, dtype: int64

#### • An internal team wants to investigate the cause of the manufacturing defects. They tell you that they want to identify as many of the ducks that have a defect as possible. Which evaluation metric would be appropriate here? Which model would be the best fit for this use case?

In [23]:
model_1 = pd.crosstab(c3_df.actual, c3_df.model1)
model_1

model1     Defect  No Defect
actual                      
Defect          8          8
No Defect       2        182

In [24]:
confusion_matrix(c3_df.actual, c3_df.model1,
                 labels = ('No Defect', 'Defect'))

array([[182,   2],
       [  8,   8]])

In [25]:
model_2 = pd.crosstab(c3_df.actual, c3_df.model2)
model_2

model2     Defect  No Defect
actual                      
Defect          9          7
No Defect      81        103

In [26]:
confusion_matrix(c3_df.actual, c3_df.model2,
                 labels = ('No Defect', 'Defect'))

array([[103,  81],
       [  7,   9]])

In [27]:
model_3 = pd.crosstab(c3_df.actual, c3_df.model3)
model_3

model3     Defect  No Defect
actual                      
Defect         13          3
No Defect      86         98

In [28]:
confusion_matrix(c3_df.actual, c3_df.model3,
                 labels = ('No Defect', 'Defect'))

array([[98, 86],
       [ 3, 13]])

In [29]:
subset = c3_df[c3_df.actual == 'Defect']
subset

actual     model1     model2     model3
13   Defect  No Defect     Defect     Defect
30   Defect     Defect  No Defect     Defect
65   Defect     Defect     Defect     Defect
70   Defect     Defect     Defect     Defect
74   Defect  No Defect  No Defect     Defect
87   Defect  No Defect     Defect     Defect
118  Defect  No Defect     Defect  No Defect
135  Defect     Defect  No Defect     Defect
140  Defect  No Defect     Defect     Defect
147  Defect     Defect  No Defect     Defect
163  Defect     Defect     Defect     Defect
171  Defect  No Defect     Defect     Defect
176  Defect  No Defect     Defect     Defect
186  Defect  No Defect  No Defect  No Defect
194  Defect     Defect  No Defect     Defect
196  Defect     Defect  No Defect  No Defect

In [32]:
# Model #1 Recall
model1_recall = (subset.actual == subset.model1).mean()
print(f'Model 1 recall {model1_recall}')
# Model #2 Recall
model2_recall = (subset.actual == subset.model2).mean()
print(f'Model 2 recall {model2_recall}')
# Model 3 Recall
model3_recall = (subset.actual == subset.model3).mean()
print(f'Model 3 recall {model3_recall}')


Model 1 recall 0.5
Model 2 recall 0.5625
Model 3 recall 0.8125


In [40]:
col = ('model1', 'model2', 'model3')
for i in col:
    # Accuracy
    (c3_df.actual == c3_df[i]).mean()
    print ({i})

{'model1'}
{'model2'}
{'model3'}


#### • Recently several stories in the local news have come out highlighting customers who received a rubber duck with a defect, and portraying C3 in a bad light. 
    The PR team has decided to launch a program that gives customers with a defective duck a vacation to Hawaii. They need you to predict which ducks will have defects, but tell you the really don't want to accidentally give out a vacation package when the duck really doesn't have a defect. 
    
    Which evaluation metric would be appropriate here? Which model would be the best fit for this use case?

    • positve case = defect 

    • negative case = no defect

In [39]:
# Model 1 with only positive predictions
subset1 = c3_df[c3_df.model1 == 'Defect']
subset1

actual  model1     model2     model3 baseline_prediction
3    No Defect  Defect     Defect     Defect              Defect
30      Defect  Defect  No Defect     Defect              Defect
62   No Defect  Defect  No Defect  No Defect              Defect
65      Defect  Defect     Defect     Defect              Defect
70      Defect  Defect     Defect     Defect              Defect
135     Defect  Defect  No Defect     Defect              Defect
147     Defect  Defect  No Defect     Defect              Defect
163     Defect  Defect     Defect     Defect              Defect
194     Defect  Defect  No Defect     Defect              Defect
196     Defect  Defect  No Defect  No Defect              Defect

In [38]:
# Model 1 precision
model1_precision = (subset.actual == subset.model1).mean()
model1_precision

0.8

In [40]:
# Model 2 with only positive predictions
subset2 = c3_df[c3_df.model2 == 'Defect']
subset2

actual     model1  model2     model3 baseline_prediction
0    No Defect  No Defect  Defect  No Defect              Defect
1    No Defect  No Defect  Defect     Defect              Defect
2    No Defect  No Defect  Defect  No Defect              Defect
3    No Defect     Defect  Defect     Defect              Defect
4    No Defect  No Defect  Defect  No Defect              Defect
..         ...        ...     ...        ...                 ...
183  No Defect  No Defect  Defect  No Defect              Defect
185  No Defect  No Defect  Defect  No Defect              Defect
193  No Defect  No Defect  Defect     Defect              Defect
195  No Defect  No Defect  Defect     Defect              Defect
198  No Defect  No Defect  Defect     Defect              Defect

[90 rows x 5 columns]

In [48]:
# Model 2 precision
model2_precision = (subset2.actual == subset2.model2).mean()
model2_precision

0.1

In [42]:
# Model 3 with only positive predictions
subset3 = c3_df[c3_df.model3 == 'Defect']
subset3

actual     model1     model2  model3 baseline_prediction
1    No Defect  No Defect     Defect  Defect              Defect
3    No Defect     Defect     Defect  Defect              Defect
5    No Defect  No Defect  No Defect  Defect              Defect
9    No Defect  No Defect  No Defect  Defect              Defect
13      Defect  No Defect     Defect  Defect              Defect
..         ...        ...        ...     ...                 ...
193  No Defect  No Defect     Defect  Defect              Defect
194     Defect     Defect  No Defect  Defect              Defect
195  No Defect  No Defect     Defect  Defect              Defect
198  No Defect  No Defect     Defect  Defect              Defect
199  No Defect  No Defect  No Defect  Defect              Defect

[99 rows x 5 columns]

In [49]:
# Model 3 precision
model3_precision = (subset3.actual == subset3.model3).mean()
model3_precision

0.13131313131313133

In [50]:
print(f'Model 1 precision {model1_precision}')
print(f'Model 2 precision {model2_precision}')
print(f'Model 3 precision {model3_precision}')

Model 1 precision 0.8
Model 2 precision 0.1
Model 3 precision 0.13131313131313133


- Takeaway 
    • Model 1 has the highest positive predictions

### 4. You are working as a data scientist for Gives You Paws ™, a subscription based service that shows you cute pictures of dogs or cats (or both for an additional fee).

    At Gives You Paws, anyone can upload pictures of their cats or dogs. The photos are then put through a two step process. First an automated algorithm tags pictures as either a cat or a dog (Phase I). Next, the photos that have been initially identified are put through another round of review, possibly with some human oversight, before being presented to the users (Phase II).

    Several models have already been developed with the data, and you can find their results here.

    Given this dataset, use pandas to create a baseline model (i.e. a model that just predicts the most common class) and answer the following questions:

In [55]:
paws_df = pd.read_csv('gives_you_paws.csv')
paws_df.head()

actual model1 model2 model3 model4
0    cat    cat    dog    cat    dog
1    dog    dog    cat    cat    dog
2    dog    cat    cat    cat    dog
3    dog    dog    dog    cat    dog
4    cat    cat    cat    dog    dog

In [56]:
paws_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   actual  5000 non-null   object
 1   model1  5000 non-null   object
 2   model2  5000 non-null   object
 3   model3  5000 non-null   object
 4   model4  5000 non-null   object
dtypes: object(5)
memory usage: 195.4+ KB


In [58]:
paws_df.value_counts()

actual  model1  model2  model3  model4
dog     dog     cat     cat     dog       644
                        dog     dog       632
                dog     dog     dog       625
                        cat     dog       590
cat     cat     cat     cat     dog       412
                        dog     dog       409
                        cat     cat       243
                        dog     cat       198
dog     cat     dog     dog     dog       170
                cat     dog     dog       155
                        cat     dog       150
                dog     cat     dog       144
cat     dog     cat     dog     dog       100
                        cat     dog        96
        cat     dog     dog     dog        57
        dog     cat     cat     cat        50
                        dog     cat        47
        cat     dog     cat     dog        47
dog     dog     cat     dog     cat        40
                dog     cat     cat        30
cat     cat     dog     cat     cat      

In [59]:
paws_df.actual.value_counts()

dog    3254
cat    1746
Name: actual, dtype: int64

In [61]:
paws_df.actual.value_counts().idxmax()

'dog'

In [63]:
# Baseline
paws_df['baseline'] = paws_df.actual.value_counts().idxmax()
paws_df

actual model1 model2 model3 model4 baseline
0       cat    cat    dog    cat    dog      dog
1       dog    dog    cat    cat    dog      dog
2       dog    cat    cat    cat    dog      dog
3       dog    dog    dog    cat    dog      dog
4       cat    cat    cat    dog    dog      dog
...     ...    ...    ...    ...    ...      ...
4995    dog    dog    dog    dog    dog      dog
4996    dog    dog    cat    cat    dog      dog
4997    dog    cat    cat    dog    dog      dog
4998    cat    cat    cat    cat    dog      dog
4999    dog    dog    dog    dog    dog      dog

[5000 rows x 6 columns]

#### a. In terms of accuracy, how do the various models compare to the baseline model? Are any of the models better than the baseline?

> • Dog = Positive class

> • Cat = Negative class

In [69]:
model_acc = []

for model in paws_df.columns[1:]:
    acc = (paws_df.actual == paws_df[model]).mean()
    model_acc.append([model, acc])
    
model_acc = pd.DataFrame(model_acc, columns = ['Model', 'Accuarcy'])
model_acc

Model  Accuarcy
0    model1    0.8074
1    model2    0.6304
2    model3    0.5096
3    model4    0.7426
4  baseline    0.6508

Takeaway - Model 1 and 4 do better than the baseline

#### b. Suppose you are working on a team that solely deals with dog pictures. Which of these models would you recommend?

#### c.Suppose you are working on a team that solely deals with cat pictures. Which of these models would you recommend?

### 5. Follow the links below to read the documentation about each function, then apply those functions to the data from the previous problem.

#### sklearn.metrics.accuracy_score

#### sklearn.metrics.precision_score

#### sklearn.metrics.recall_score

#### sklearn.metrics.classification_report