# Evaluation

## Exercises

### 1. Create a new file named model_evaluation.py or model_evaluation.ipynb for these exercises.

### 2. Given the following confusion matrix, evaluate (by hand) the model's performance.


|                  | (AP) actual dog     | (AN) actual cat|                          |
|:-----------------|--------------------:|---------------:|--------------------------:
| (PP) pred dog    | (TP)             46 | (FP)        13 | Precision/PPV:TP/(TP+FP) |
| (PN) pred cat    | (FN)              7 | (TN)        34 | NPV: TN/(TN_FN).         |
|                  | Recall/Sensitivity: | Specificity:   | Accuracy =               |
|                  | TP/(TP+FN)          | TN/(FP+TN)     | (TP+TN)/                 |
|                  |                     |                | (TP+FP+FN+TN)            |


>In the context of this problem, what is a false positive?
>> FP: We predicted they were dogs and they were actual cats (13 times)

>In the context of this problem, what is a false negative?
>> FN: We predicted they were cats and they were actual dogs (7 times)

>How would you describe this model?
>> TP: We predicted they were dogs and they were actual dogs (46 times)

>> TN: We predicted they were cats and they were actual cats (34 times)

>> FP: We predicted they were dogs and they were actual cats (13 times)

>> FN: We predicted they were cats and they were actual dogs (7 times)

In [36]:
TP = 46

TN = 34

FP = 13

FN = 7

### 3. You are working as a datascientist working for Codeup Cody Creator (C3 for short), a rubber-duck manufacturing plant.

    Unfortunately, some of the rubber ducks that are produced will have defects. Your team has built several models that try to predict those defects, and the data from their predictions can be found here.

    Use the predictions dataset and pandas to help answer the following questions:

### Imports

In [6]:
import pandas as pd

#stats
from sklearn.metrics import confusion_matrix

In [7]:
filename = 'c3.csv'

In [14]:
c3_df = pd.read_csv(filename)

In [15]:
c3_df.head()

actual     model1  model2     model3
0  No Defect  No Defect  Defect  No Defect
1  No Defect  No Defect  Defect     Defect
2  No Defect  No Defect  Defect  No Defect
3  No Defect     Defect  Defect     Defect
4  No Defect  No Defect  Defect  No Defect

#### • An internal team wants to investigate the cause of the manufacturing defects. They tell you that they want to identify as many of the ducks that have a defect as possible. Which evaluation metric would be appropriate here? Which model would be the best fit for this use case?

In [22]:
model_1 = pd.crosstab(c3_df.actual, c3_df.model1)
model_1

model1     Defect  No Defect
actual                      
Defect          8          8
No Defect       2        182

In [27]:
confusion_matrix(c3_df.actual, c3_df.model1,
                 labels = ('No Defect', 'Defect'))

array([[182,   2],
       [  8,   8]])

In [23]:
model_2 = pd.crosstab(c3_df.actual, c3_df.model2)
model_2

model2     Defect  No Defect
actual                      
Defect          9          7
No Defect      81        103

In [28]:
confusion_matrix(c3_df.actual, c3_df.model2,
                 labels = ('No Defect', 'Defect'))

array([[103,  81],
       [  7,   9]])

In [24]:
model_3 = pd.crosstab(c3_df.actual, c3_df.model3)
model_3

model3     Defect  No Defect
actual                      
Defect         13          3
No Defect      86         98

In [29]:
confusion_matrix(c3_df.actual, c3_df.model3,
                 labels = ('No Defect', 'Defect'))

array([[98, 86],
       [ 3, 13]])

In [32]:
c3_df.actual.value_counts()

No Defect    184
Defect        16
Name: actual, dtype: int64

In [34]:
c3_df['baseline_prediction'] = 'Defect'

In [35]:
c3_df.head()

actual     model1  model2     model3 baseline_prediction
0  No Defect  No Defect  Defect  No Defect              Defect
1  No Defect  No Defect  Defect     Defect              Defect
2  No Defect  No Defect  Defect  No Defect              Defect
3  No Defect     Defect  Defect     Defect              Defect
4  No Defect  No Defect  Defect  No Defect              Defect

In [ ]:
subset = c3_df

In [41]:
model1_recall = (dubset.actual == subset.model1).mean()
model2_recall = (dubset.actual == subset.model2).mean()
model3_recall = (dubset.actual == subset.model3).mean()

print(f"""Model 1 Recall: {model1_recall:.2%})
print(model2_recall:.2%)
print(model3_recall:.2%)

SyntaxError: unexpected EOF while parsing (2637296198.py, line 7)

In [40]:
col = ('model1', 'model2', 'model3')
for i in col:
    # Accuracy
    (c3_df.actual == c3_df[i]).mean()
    print ({i})

{'model1'}
{'model2'}
{'model3'}


#### • Recently several stories in the local news have come out highlighting customers who received a rubber duck with a defect, and portraying C3 in a bad light. The PR team has decided to launch a program that gives customers with a defective duck a vacation to Hawaii. They need you to predict which ducks will have defects, but tell you the really don't want to accidentally give out a vacation package when the duck really doesn't have a defect. Which evaluation metric would be appropriate here? Which model would be the best fit for this use case?

• positve case = defect 

• negative case = no defect

In [ ]:
# 
model1_precision = (subset.actual == subset.model1).mean()
model1_precision

In [ ]:
subset2 = c3_df [c3_df.model2 == 'Defect')
                 

In [31]:
model_accuracy = (c3_df.model1 == c3_df.actual).mean()
baseline_accuracy = (c3_df.baseline_model1 == c3_df.actual).mean()

print(f'   model accuracy: {model_accuracy:.2%}')
print(f'baseline accuracy: {baseline_accuracy:.2%}')

AttributeError: 'DataFrame' object has no attribute 'baseline_model1'